services:
  backend_node:
    container_name: backend_node
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "81:3000"
    environment:
      PORT: ${PORT}
    depends_on:
     - base_datos_mysql
    restart: unless-stopped
  
  base_datos_mysql:
    container_name: base_datos_mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bd_base_defecto
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_service:/var/lib/mysql
    restart: unless-stopped
  
  db_phpmyadmin:
    container_name: db_phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: base_datos_mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "7777:80"
    depends_on:
      - base_datos_mysql
    restart: unless-stopped

volumes:
  mysql_data_service: